name: ubuntu-gcc13

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Installation
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip wget
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt install -y gcc-13 g++-13

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v3.0.7

      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          export XMAKE_ROOT="y"
          g++-13 -v
          export CXX=g++-13
          export CC=gcc-13
          xmake build -y
          xmake install -o .
